name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    if: github.event.pull_request.merged == 'true'
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main
      - name: Update README.md
        run: |
          curl -s https://api.github.com/repos/${{ github.repository }}/pulls -o README.md

          # Commit and push the changes to the repository
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "README.md updated"
          git push
